server:
  port: 2222
  servlet:
    context-path: /

#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resourse?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useUnicode=true
    username: root
    password: 123456
  thymeleaf:
    cache: false   #关闭thymeleaf缓存
imgFilePath: D:/idea/bysj/src/main/resources/static/img/